scrollback_lines 10000

visual_bell_duration 0.0
enable_audio_bell no

term xterm-kitty

# Ctrl-Enter
map ctrl+enter send_text all \x1b_KreX\x1b\\

tab_bar_style        powerline
tab_powerline_style  slanted


include tokyonight.conf

font_family      family="CaskaydiaCove Nerd Font"
font_size 11.0
