general {
    lock_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = loginctl lock-session && hyprctl dispatch dpms on
}

# Lock after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Screen off after 6 minutes (after lock)
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend system after 10 minutes
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
